#!/bin/bash
###########################################################################################
####                                    COMPILER                                       ####
####                              gfortran-## + gcc-##                                 ####
####                                  ifx     + icx                                    ####
###########################################################################################
fc="gfortran-12"
cc="gcc-12"

###########################################################################################
####                               INSTRUCTIONS CHECK                                  ####
###########################################################################################
macros=$($cc -march=native -dM -E -x c /dev/null)

echo "$macros" | grep -q "__FMA__"     && instructions="$instructions -D__FMA__"
echo "$macros" | grep -q "__AVX512F__" && instructions="$instructions -D__AVX512F__"

###########################################################################################
####                                 COMPILER SET UP                                   ####
###########################################################################################
case $fc in
    ifx)
        flags="-O3 -ipo -xHost -fp-model=fast -fomit-frame-pointer -qopt-zmm-usage=high \
               -fno-stack-protector -qopenmp-simd -fno-alias $instructions"
        
        fcompile="$fc $flags -cpp"
        ccompile="$cc $flags -fno-builtin-memcpy -fno-builtin-memmove -fno-builtin-memset"
    ;;
    
    gfortran*)
        flags="-Ofast -march=native -mprefer-vector-width=512 -mno-vzeroupper -fstrict-aliasing \
               -fno-tree-loop-distribute-patterns -fcx-limited-range -fno-bounds-check -fopenmp-simd \
               -fomit-frame-pointer -fno-stack-protector -fargument-noalias-global -flto=auto \
               -fwhole-program $instructions -cpp"
        
        fcompile="$fc $flags"
        ccompile="$cc $flags -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-memmove"
    ;;
esac

###########################################################################################
####                                PATHS TO LIBRARIES                                 ####
###########################################################################################
mathpath=src/math
fftpath=src/fft
legepath=src/lgp
gridpath=src/grid
sphpath=src/sph
srcpath=src

###########################################################################################
####                                  DIRS STRUCTURE                                   ####
###########################################################################################
lvlC=( "${mathpath}/smod/codelets" 
       "${legepath}/smod/codelets" 
       "${fftpath}/smod/codelets" )

lvlF=( "${mathpath}/smod" 
       "${fftpath}/smod/init" 
       "${fftpath}/smod/transform" 
       "${legepath}/smod/init" 
       "${legepath}/smod/cores" 
       "${legepath}/smod/transform" 
       "${sphpath}/smod/init" 
       "${sphpath}/smod/cores" 
       "${gridpath}/smod/" )

###########################################################################################
####                               1. COMPILING INTERFACES                             ####
###########################################################################################
$fcompile -c "${mathpath}/math.f90"
$fcompile -c "${fftpath}/fourier_transform.f90"
$fcompile -c "${legepath}/lege_poly.f90"
$fcompile -c "${gridpath}/physical_grid.f90"
$fcompile -c "${sphpath}/lateral_grid.f90"
$fcompile -c "${srcpath}/sphsingle.f90"

###########################################################################################
####                           2. COMPILING IMPLEMENTATIONS                            ####
###########################################################################################
find "${lvlC[@]}" -maxdepth 1 -name "*.c"   -print0 | xargs -0 -r -P 0 -n 1 $ccompile -c &
find "${lvlF[@]}" -maxdepth 1 -name "*.f90" -print0 | xargs -0 -r -P 0 -n 1 $fcompile -c &

wait

###########################################################################################
####                           3. LINKING TO MAIN CODE                                 ####
###########################################################################################
$fcompile -fopenmp test.f90 *.o -o sph_test

###########################################################################################
####                                    CLEANING                                       ####
###########################################################################################
rm *.smod *.mod *.o || true