#!/bin/bash
###########################################################################################
####                              COMPILER CHOICE                                      ####
###########################################################################################
compiler="gfortran"
instructions="avx"

###########################################################################################
####                              COMPILER SET UP                                      ####
###########################################################################################
if [ "$compiler" = "gfortran" ];
then
  fcompile="gfortran-12 -Ofast \
                        -march=native \
                        -mprefer-vector-width=512 \
                        -fno-bounds-check \
                        -flto=auto \
                        -fwhole-program \
                        -fopenmp \
                        -cpp -D$instructions"
  
  ccompile="gcc-12 -Ofast \
                   -fno-strict-aliasing \
                   -fomit-frame-pointer \
                   -march=native \
                   -mprefer-vector-width=512 \
                   -flto=auto \
                   -fwhole-program \
                   -cpp -D$instructions"

elif [ "$compiler" = "ifx" ];
then
  fcompile="ifx -fast \
                -Ofast \
                -ipo \
                -ffast-math \
                -funroll-loops \
                -xHost \
                -qopt-zmm-usage=high \
                -qopenmp \
                -cpp -D$instructions"
  
  ccompile="icx -fast \
                -Ofast \
                -no-ansi-alias \
                -ipo \
                -ffast-math \
                -funroll-loops \
                -xHost \
                -qopt-zmm-usage=high \
                -D$instructions"

elif [ "$compiler" = "ifort" ];
then
  fcompile="ifort -fast \
                  -Ofast \
                  -ipo \
                  -ffast-math \
                  -funroll-loops \
                  -xHost \
                  -qopt-zmm-usage=high \
                  -qopenmp \
                  -diag-disable=10448 \
                  -diag-disable=11003 \
                  -diag-disable=11021 \
                  -cpp -D$instructions"
  
  ccompile="icx -fast \
                -Ofast \
                -no-ansi-alias \
                -ffast-math \
                -funroll-loops \
                -xHost \
                -qopt-zmm-usage=high \
                -D$instructions"
fi

###########################################################################################
####                            BUILDING OBJ INTERFACES                                ####
###########################################################################################
$fcompile -c src/math/math.f90
$fcompile -c src/fft/fourier_transform.f90
$fcompile -c src/lgp/lege_poly.f90
$fcompile -c src/sph/lateral_grid.f90
$fcompile -c src/sphpack.f90

###########################################################################################
####                         BUILDING FORTRAN IMPLEMENTATIONS                          ####
###########################################################################################
$fcompile -c src/math/arr/alloc.f90 &
$fcompile -c src/fft/init/*.f90 &
$fcompile -c src/fft/cores/*.f90 &
$fcompile -c src/fft/transform/*.f90 &
$fcompile -c src/lgp/init/*.f90 &
$fcompile -c src/lgp/indexing/*.f90 &
$fcompile -c src/lgp/transform/*.f90 &
$fcompile -c src/sph/init/*.f90 &
$fcompile -c src/sph/cores/*.f90 &
wait

###########################################################################################
####                            BUILDING CORE IMPLEMENTATIONS                          ####
###########################################################################################
if [ "$instructions" = "f90" ];
then
  $fcompile -c src/math/arr/f90/arrzero.f90 &
  $fcompile -c src/math/arr/f90/arrcopy.f90 &
  $fcompile -c src/lgp/codelets/f90/*.f90 &
  $fcompile -c src/fft/codelets/f90/*.f90 &
  wait
else
  $ccompile -c src/math/arr/cvec/arrzero.c &
  $ccompile -c src/math/arr/cvec/arrcopy.c &
  $ccompile -c src/lgp/codelets/cvec/*.c &
  $ccompile -c src/fft/codelets/cvec/*.c &
  wait
fi

###########################################################################################
####                              LINKING TO MAIN CODE                                 ####
###########################################################################################
$fcompile test.f90 *.o -o sph_test

###########################################################################################
####                                      CLEANING                                     ####
###########################################################################################
rm *.o *.mod *.smod
